export let initialData = [
  {
    id: 1,
    name: 'Shoping List',
    created: '20-05-2021',
    category: 'task',
    content: 'tomatoes, vegetables',
    dates: '21-05-2021',
    archivated: false,
  },
  {
    id: 2,
    name: 'Nice Theory',
    created: '17-04-2021',
    category: 'random thought',
    content: 'Random long text...',
    dates: null,
    archivated: false,
  },
  {
    id: 3,
    name: 'New Feature',
    created: '05-04-2021',
    category: 'idea',
    content: 'Random long text...',
    dates: null,
    archivated: false,
  },
  {
    id: 4,
    name: 'William Gaddis',
    created: '27-03-2021',
    category: 'quote',
    content: 'Random long text...',
    dates: null,
    archivated: false,
  },
  {
    id: 5,
    name: 'Books',
    created: '15-05-2021',
    category: 'task',
    content: 'Super Sturtup',
    dates: null,
    archivated: false,
  },
  {
    id: 6,
    name: 'Test',
    created: '16-05-2021',
    category: 'task',
    content: 'Test tekst',
    dates: null,
    archivated: true,
  },
  {
    id: 7,
    name: 'Test2',
    created: '17-05-2021',
    category: 'idea',
    content: 'Test tekst',
    dates: null,
    archivated: true,
  },
  {
    id: 8,
    name: 'Test3',
    created: '18-05-2021',
    category: 'random thought',
    content: 'Test tekst',
    dates: null,
    archivated: true,
  },
];
